// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RealEstate.Data.Context;

#nullable disable

namespace RealEstate.Data.Migrations
{
    [DbContext(typeof(RealEstateDbContext))]
    [Migration("20230804141608_NewInitaialMigration")]
    partial class NewInitaialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("RealEstate.Domain.Entities.Auth.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("JwtExpiryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("JwtId")
                        .HasColumnType("longtext");

                    b.Property<string>("Token")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("RealEstate.Domain.Entities.Core.AuthUser.OneTimeCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ExpiringDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Sender")
                        .HasColumnType("longtext");

                    b.Property<string>("Token")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("OneTimeCode");
                });

            modelBuilder.Entity("RealEstate.Domain.Entities.Core.PropertyUpload", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Amount")
                        .HasColumnType("longtext");

                    b.Property<string>("Area")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Furnished")
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUpload")
                        .HasColumnType("longtext");

                    b.Property<string>("InstallmentalPayment")
                        .HasColumnType("longtext");

                    b.Property<string>("Locality")
                        .HasColumnType("longtext");

                    b.Property<string>("NewlyBuilt")
                        .HasColumnType("longtext");

                    b.Property<string>("NumbersOfBathroom")
                        .HasColumnType("longtext");

                    b.Property<string>("NumbersOfRoom")
                        .HasColumnType("longtext");

                    b.Property<string>("NumbersOfToilet")
                        .HasColumnType("longtext");

                    b.Property<string>("PropertyType")
                        .HasColumnType("longtext");

                    b.Property<string>("Purpose")
                        .HasColumnType("longtext");

                    b.Property<string>("Serviced")
                        .HasColumnType("longtext");

                    b.Property<string>("State")
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("PropertyUploads");
                });

            modelBuilder.Entity("RealEstate.Domain.Entities.ErrorLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateOnly>("DateLogged")
                        .HasColumnType("date");

                    b.Property<string>("Message")
                        .HasColumnType("longtext");

                    b.Property<string>("RequestUri")
                        .HasColumnType("longtext");

                    b.Property<TimeOnly>("TimeLogged")
                        .HasColumnType("time(6)");

                    b.HasKey("Id");

                    b.ToTable("ErrorLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
